apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: 'nginx' # queremos criar um controller baseado no projeto NGINX
    nginx.ingress.kubernetes.io/use-regex: 'true' # usar regex para direcionar erros 404 para localhost
    nginx.ingress.kubernetes.io/rewrite-target: /$1 # como a cópia do NGINX vai se comportar
spec:
  rules:
    - http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-cluster-ip-service
                port:
                  number: 3000
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: server-cluster-ip-service
                port: 
                  number: 5000